### ISSUE TITLE
Create Fourier Tracing Tracer Bullet

### ISSUE THREAD

**Issue by ZenPylon** [ZenPylon/zenpylon-me#5]
# Summary
Add the Fourier Tracing page and create an interactive tool for exploration.

# Implementation Plan

## PR 1

- [ ] Add 4-point 2D plot with Plotly for proof of concept
- [ ] Add a `calcFourierSeries()` function that accepts a list of coefficients and x values, and returns the value of that function for each x coordinate
- [ ] Call `calcFourierSeries()` for the template and target functions, and plot the two functions.  Template color should be blue, target color should be red.  Add a third plot to represent the morph function, starting with the same structure as the template plot

## PR 2

- [ ] Add property `fourierCoefficients[]`, which is an object containing `target` and `template` properties 
- [ ] Add a part of the template that creates an `ion-range` for every element of `fourierCoefficients`
- [ ] Add an event handler `onCoefficientDrag` which responds to the coefficient slide events.  `onCoeffiicentDrag` should call `calcFourierSeries` with the interpolated coefficient values, and should update the morph plot with those values.  Should also set the color to be interpolated between red and blue based on how far the function has morphed (average the `current / Maths.abs(rangeMax - rangeMin)` across all the sliders)

## PR 3

- [ ] Add an `ion-range` with an event handler `onMorphValueChange`, which interpolates all the Fourier sliders and then updates the plot 

## PR 3

- [ ] Add an `ion-range` with an event handler `onNumTermsChange` that prints the range value
- [ ] Update `onTermsRangeChange` to modify `fourierCoefficients` according to the desired number of terms.  Use dummy data initially
